server:
  port: 8082
  servlet:
    context-path: /auth
spring:
  application:
    name: auth
  datasource:
    driverClassName: org.h2.Driver
    password: 'nlpass'
    url: jdbc:h2:mem:netxlevel
    username: nextlevel
    h2:
      console:
        enabled: true
        path: /h2-console
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
    security:
      filter:
        order: 10
      jwt:
        chave-assinatura: "Ym9tIGRpYSBxdWUgbyBzb2wgamEgbmFzY2V1"
        expiracao: 30